Repository elastic/go-libaudit, pull requests merged in 2022-02, with the labels that each got.

#92 Simplify message serialisation code and test
  audit.go
  audit_test.go
  netlink.go
  rule/binary.go
  rule/rule.go
  rule/rule_test.go
Labels: Team:Security-External Integrations

#101 all: remove use of pkg/errors and replace with standard library
  .go-version
  aucoalesce/coalesce.go
  aucoalesce/mknormalize_data.go
  aucoalesce/normalize.go
  audit.go
  audit_test.go
  auparse/auparse.go
  auparse/auparse_test.go
  auparse/defs_audit_arches.go
  auparse/hex.go
  auparse/mk_audit_exit_codes.go
  auparse/mk_audit_msg_types.go
  cmd/audit/audit.go
  cmd/auparse/auparse.go
  go.mod
  go.sum
  netlink.go
  netlink_test.go
  reassembler.go
  rule/defs_kernel_types.go
  rule/gen_testdata_test.go
  rule/rule.go
  rule/rule_integ_test.go
Labels: enhancement, Team:Security-External Integrations

#98 Add ECS normalizations for TIME_ADJNTPVAL and TIME_INJOFFSET
  CHANGELOG.md
  aucoalesce/normalizations.yaml
  aucoalesce/testdata/random-internet.json.golden
  aucoalesce/testdata/random-internet.yaml
  aucoalesce/testdata/ubuntu-21.10-linux-5.13.json.golden
  aucoalesce/testdata/ubuntu-21.10-linux-5.13.yaml
  aucoalesce/znormalize_data.go
Labels: enhancement, Team:Security-External Integrations

#102 auparse: update codegen to include new build constraint syntax
  auparse/mk_audit_arches.pl
Labels: enhancement, Team:Security-External Integrations

#97 Allow exe exclude rules
  CHANGELOG.md
  Vagrantfile
  rule/rule.go
  rule/testdata/20-dont-audit.rules
  rule/testdata/20-dont-audit.rules.golden.yml
  rule/testdata/22-ignore-chrony.rules.golden.yml
  rule/testdata/30-nispom.rules.golden.yml
  rule/testdata/30-pci-dss-v31.rules.golden.yml
  rule/testdata/30-stig.rules.golden.yml
  rule/testdata/32-power-abuse.rules.golden.yml
  rule/testdata/41-containers.rules.golden.yml
  rule/testdata/42-injection.rules.golden.yml
  rule/testdata/43-module-load.rules.golden.yml
  rule/testdata/70-einval.rules.golden.yml
  rule/testdata/71-networking.rules.golden.yml
Labels: enhancement, Team:Security-External Integrations

#103 Fix error message from AddRule
  CHANGELOG.md
  audit.go
Labels: bug

#104 Use Go embed for normalizations.yaml data
  .editorconfig
  CHANGELOG.md
  Vagrantfile
  aucoalesce/mknormalize_data.go
  aucoalesce/normalize.go
  aucoalesce/znormalize_data.go
  go.mod
Labels: enhancement, Team:Security-External Integrations
